services:
    jdatetime:
        class: farhadi\IntlDateTime

    pouya_soft.sdate_extension:
        class: PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension
        arguments: [ @jdatetime ]
        tags:
            - { name: twig.extension }

    pouya_soft.form.type.j_sdate:
        class: PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType
        tags:
            - { name: form.type, alias: jSDate }
        arguments: [@jdatetime]