services:
    pouya_soft.j_sdate_service:
        class: PouyaSoft\SDateBundle\Service\jDateService
        arguments: ["@request_stack"]

    pouya_soft.sdate_extension:
        class: PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension
        arguments: [ "@pouya_soft.j_sdate_service" ]
        tags:
            - { name: twig.extension }

    pouya_soft.form.type.j_sdate:
        class: PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType
        tags:
            - { name: form.type, alias: jSDate }
        arguments: [ "@pouya_soft.j_sdate_service", "@request_stack" ]