services:
    pouya_soft.j_sdate_service:
        class: PouyaSoft\SDateBundle\Service\jDateService
        arguments: ["@request_stack"]
        public: true

    pouya_soft.sdate_extension:
        class: PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension
        arguments: [ "@pouya_soft.j_sdate_service" ]
        tags:
            - { name: twig.extension }
        public: true

    pouya_soft.form.type.j_sdate:
        class: PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType
        tags:
            - { name: form.type, alias: jSDate }
        arguments: [ "@pouya_soft.j_sdate_service", "@request_stack" ]
        public: true

    pouya_soft.form.type.persian_sdate:
        class: PouyaSoft\SDateBundle\Form\Type\PouyaSoftPersianSDateType
        tags:
            - { name: form.type, alias: persianSDate }
        public: true

    PouyaSoft\SDateBundle\Service\jDateService: '@pouya_soft.j_sdate_service'
    PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension: '@pouya_soft.sdate_extension'
    PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType: '@pouya_soft.form.type.j_sdate'
    PouyaSoft\SDateBundle\Form\Type\PouyaSoftPersianSDateType: '@pouya_soft.form.type.persian_sdate'