services:
    PouyaSoft\SDateBundle\Service\jDateService:
        alias: 'pouya_soft.j_sdate_service'
        arguments: ["@request_stack"]
        public: true

    PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension:
        alias: 'pouya_soft.sdate_extension'
        tags: ['twig.extension']
        arguments: [ "@pouya_soft.j_sdate_service" ]
        public: true

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType:
        alias: 'jSDate'
        tags: ['form.type']
        arguments: [ "@pouya_soft.j_sdate_service", "@request_stack" ]
        public: true

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftPersianSDateType:
        alias: 'persianSDate'
        tags: ['form.type']
        public: true