services:
    PouyaSoft\SDateBundle\Service\jDateService:
        arguments: ["@request_stack"]
        public: true

    PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension:
        tags: ['twig.extension']
        arguments: [ "@pouya_soft.j_sdate_service" ]
        public: true

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType:
        tags: ['form.type']
        arguments: [ "@pouya_soft.j_sdate_service", "@request_stack" ]
        public: true

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftPersianSDateType:
        tags: ['form.type']
        public: true