services:
    PouyaSoft\SDateBundle\Service\jDateService:
        arguments: ["@request_stack"]
        public: true

    pouya_soft.j_sdate_service:
        alias: PouyaSoft\SDateBundle\Service\jDateService

    PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension:
        tags: ['twig.extension']
        arguments: [ "@pouya_soft.j_sdate_service" ]
        public: true

    pouya_soft.sdate_extension:
        alias: PouyaSoft\SDateBundle\Twig\PouyaSoftDateExtension

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftSDateType:
        alias: 'jSDate'
        tags: ['form.type']
        arguments: [ "@pouya_soft.j_sdate_service", "@request_stack" ]
        public: true

    PouyaSoft\SDateBundle\Form\Type\PouyaSoftPersianSDateType:
        alias: 'persianSDate'
        tags: ['form.type']
        public: true